apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mermaid-mcp

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: michaelfay/mermaid-mcp
    newTag: latest
